name: Dockerized App Deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 24700
          script: |
            cd /root/dmojfe
            git fetch origin
            git checkout production
            git pull origin production
            docker build -t dmojfe:latest .
            docker stop dmojfe-container || true
            docker rm dmojfe-container || true
            docker run -d \
            --name dmojfe-container \
            -p 4000:3000 \
            dmojfe:latest


